before:
  hooks:
    - go mod download
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  main: ./main.go
  goos:
    - windows
    - linux
    - darwin
archives:
  -
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: binary
  -
    id: homebrew
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: fuzzit

    github:
      owner: fuzzitdev
      name: fuzzit

    url_template: "https://github.com/fuzzitdev/fuzzit/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # Your app's homepage.
    # Default is empty.
    homepage: "https://fuzzit.dev"

    # Your app's description.
    # Default is empty.
    description: "Continuous Fuzzing Made Simple."